### ISSUE TITLE
QA-Vshop login screen-Social Media login not working.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/virtual-shop-data#20]
QA-Vshop login screen-Social Media login not working.

Test Scenarios
***************
1. User Should be able Login with Social Media.

**Comment by emp005169** [comment]
social media login dependency is live now. you can continue on this issue.

**Comment by qajha** [comment]
Issue is not resolved yet and showing internal server error when user fill the details of LinkedIn.

**Comment by Nikunj025** [comment]
Done
