### ISSUE TITLE
QA-Product Count mismatch on live site

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/virtual-shop-data#23]
Product Count mismatch on live site

**Comment by Zalasanjay** [comment]
i have check this issue by registering new user ( Username: johndoes@yopmail.com Password: 123123 ) and i buy new Test-QA subscription plan then create new Virtual Shop (vid: fa5215e9-3b97-410e-b190-4a92d897c0f1, name: Testing_1) with 99 Products, Then publish a new eCommerce website by using Testing_1 Virtual Shop Data. So, in website front-end it showing complete 99 Products in total.

**Comment by Nikunj025** [comment]
Still Count is mismatched.
Case is already discuss with Sanjay and Ashwini.

**Comment by Zalasanjay** [comment]
Bug is fixed.
