### ISSUE TITLE
QA-Suggestions

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/virtual-shop-data#26]
1. Id should be replaced with Virtual Shop Id
2. A user should be displayed if login available in our other modules.
3. Search product textbox should be disabled till supplier not selected.
4. Supplier name should be alphabetical order.

**Comment by Zalasanjay** [comment]
6. Also done validation when not selected any product and then submit by filling name only.

**Comment by Nikunj025** [comment]
Point 3 is pending in development end and other rest point is done in QA end,so next release the devloper provide the point 3 change.
