### ISSUE TITLE
QA-Two Entries should not be display if User Create its First Distributor Data.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/virtual-shop-data#32]
QA-Two Entries should not be display if User Create its First Distributor Data.

![multiple entry](https://user-images.githubusercontent.com/36195435/37134483-c0e47ab0-22be-11e8-9a7b-265d3e5fb0a7.jpg)

**Comment by Zalasanjay** [comment]
i have check it out several time on both servers QA and Development and this type of issue is not reproduced. so i request you to close this issue.

**Comment by Nikunj025** [comment]
Done

**Comment by qajha** [comment]
Issue is resolved now in QA server
