### ISSUE TITLE
QA-when user select the theme option 5 then flowz logo is not showing due to white background image.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/virtual-shop-data#35]
When user select the theme option 5 then flowz logo is not showing due to white background image.
![vshop1](https://user-images.githubusercontent.com/36195435/37153246-12f83a10-2302-11e8-8733-ed88d15b3344.png)

**Comment by Nikunj025** [comment]
Done.
Only 4 Themes available now.

**Comment by qajha** [comment]
Issue is resolved now in QA server
