### ISSUE TITLE
QA-Suggestion-Please replace with Name to Virtual Shop Name" and same in validation message if field is blank and user click on submit button.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/virtual-shop-data#54]
Please replace with Name to Virtual Shop Name" and same in validation message if field is blank and user click on submit button.

**Comment by Nikunj025** [comment]
In Error Message It Should be display in Capitalized Not In Upper Case.

**Comment by Nikunj025** [comment]
Done
