### ISSUE TITLE
QA-Virtual Shop-When user select the 1000 thousand supplier data and enter the virtual name and click on submit button system is showing the pending status for max time.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/virtual-shop-data#55]
When the user selects the 1000 thousand supplier data and enter the virtual name and click on submit button system is showing the pending status for a max time.

**Comment by Zalasanjay** [comment]
this scenario is tested several time on both the servers (Development and QA) and this type of issue is not happening.

**Comment by Nikunj025** [comment]
Done
