### ISSUE TITLE
QA - Virtual Shop Data - Need to Display Favicon icon for Virtual Shop Data in Browser Tab.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/virtual-shop-data#71]
QA - Virtual Shop Data - Need to Display Favicon icon for Virtual Shop Data in Browser Tab.

For Favicon icon refer Flowz Builder.

![need to display favicon icon for virtual shop data in browser tab](https://user-images.githubusercontent.com/36226408/37900134-ef2668a2-310a-11e8-814f-9d553744e5af.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
